# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing
import rnet

def delete(url:builtins.str, **kwds) -> Response:
    r"""
    Shortcut method to quickly make a `DELETE` request.
    """
    ...

def get(url:builtins.str, **kwds) -> Response:
    r"""
    Shortcut method to quickly make a `GET` request.
    """
    ...

def head(url:builtins.str, **kwds) -> Response:
    r"""
    Shortcut method to quickly make a `HEAD` request.
    """
    ...

def options(url:builtins.str, **kwds) -> Response:
    r"""
    Shortcut method to quickly make an `OPTIONS` request.
    """
    ...

def patch(url:builtins.str, **kwds) -> Response:
    r"""
    Shortcut method to quickly make a `PATCH` request.
    """
    ...

def post(url:builtins.str, **kwds) -> Response:
    r"""
    Shortcut method to quickly make a `POST` request.
    """
    ...

def put(url:builtins.str, **kwds) -> Response:
    r"""
    Shortcut method to quickly make a `PUT` request.
    """
    ...

def request(method:Method, url:builtins.str, **kwds) -> Response:
    r"""
    Make a request with the given parameters.
    """
    ...

def trace(url:builtins.str, **kwds) -> Response:
    r"""
    Shortcut method to quickly make a `TRACE` request.
    """
    ...

def websocket(url:builtins.str, **kwds) -> WebSocket:
    r"""
    Make a WebSocket connection with the given parameters.
    
    This function allows you to make a WebSocket connection with the specified parameters encapsulated in a `WebSocket` object.
    """
    ...

